version: '2'
services:
    dynamicfiltrationpagination-sonar:
        container_name: dynamicfiltrationpagination-sonar
        image: sonarqube:6.1-alpine
        ports:
            - 9000:9000
            - 9092:9092
